config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'books/index'
  get 'books/new'
  root 'static_pages#home'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/about', to: 'static_pages#about'
  resources :books do
    collection do
      get 'search'
    end
  end
  resources :books, only: %i[index show edit update] do
    member do
      # 追加したeditとupdateアクション
      get 'edit_detail'
      patch 'update_detail'
    end
  end
  resources :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :place
  mount_uploader :picture, PictureUploader
  validate :picture_size

  paginates_per 16

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    errors.add(:picture, 'should be less than 2MB') if picture.size > 5.megabytes
  end
end

app/models/lending.rb
# frozen_string_literal: true

class Lending < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
  has_many :books
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@chiba-u.jp/.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show]
  before_action :logged_in_user

  def new
    @places = Place.all
    @book = Book.new
  end

  def index
    @books = Book.order(updated_at: "DESC").page params[:page]
    @books_count = Book.all.count
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @book.image_url = @book.picture.url if @book.picture?
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @book.image_url = @book.picture.url if @book.picture?
  end

  def edit_detail
    @book = Book.find(params[:id])
    @book.image_url = @book.picture.url if @book.picture?
  end

  def update
    @user = current_user
    @book = Book.find(params[:id])
    @book.image_url = @book.picture.url if @book.picture?
    if @book.update(book_params)
      flash[:success] = 'Information updated'
      redirect_to @book
    else
      render 'edit'
    end
  end

  def update_detail
    @book = Book.find(params[:id])
    @book.image_url = @book.picture.url if @book.picture?
    if @book.update(book_params)
      flash[:danger] = 'Please save change'
      redirect_to edit_book_path
    else
      render 'edit'
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = 'Book deleted'
    redirect_to books_url
  end

  def search
    @books = Book.where(['title LIKE(?) OR author LIKE(?)', "%#{params[:keyword]}%", "%#{params[:keyword]}%"])
    respond_to do |format|
      format.json { render 'index', json: @books }
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :isbn, :image_url, :publish_date, :last_rental, :updated_at,
                                 :publisher, :page_count, :textship, :description, :place_id, :picture)
  end

  def user_params
    params.require(:user).permit(:name, :last_rental)
  end

  def textship_params
    params.permit(:textship)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def logged_in_user
    if logged_in?
    else
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end
end

app/controllers/lending_controller.rb
# frozen_string_literal: true

class LendingController < ApplicationController
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user.present?
      log_in user
      flash[:success] = 'log in'
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = 'log out'
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def about; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/helpers/lending_helper.rb
# frozen_string_literal: true

module LendingHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/books/_isbn_reader.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  ISBN READER
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ISBNをカメラ内に入れてください</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="interactive" class="viewport isbn-reader"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<%= javascript_pack_tag 'book/new.js' %>


<div class="row">
	<div class="col">
		<h1 class="text-center mt-5">Edit</h1>
    <div class="text-center mt-4 mb-4">
    <img src="<%= @book.image_url %>" alt=""　height="130">
    </div>
		<%= form_with model: @book, url: update_detail_book_path(@book), local: true do |f| %>
　　　　<div class="form-group text-center">
       <div class="col-12">
			　<%= f.label :picture, class: 'bmd-label-floating' %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
			</div>
			</div>
			<div class="form-row text-center">
      <div class="col-12">
      <%= f.submit "upload", class: "btn btn-outline-primary" %>
      </div>
　　　 </div>
　  <% end %>
		<%= form_with model: @book ,local: true do |f| %>			
			<div class="form-group">
				<%= f.label :place_id , class: 'bmd-label-floating' %>
				<%= f.collection_select :place_id, Place.all, :id, :name, {prompt: true} ,{:class => "form-control"} %>
			</div>
			
			<div class="form-group">
				<%= f.label :title, class: 'bmd-label-floating' %><span class="red">*</span>
				<%= f.text_field :title, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :author, class: 'bmd-label-floating' %>
				<%= f.text_field :author, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :publisher, class: 'bmd-label-floating' %>
				<%= f.text_field :publisher, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :publish_date, class: 'bmd-label-floating' %>
				<%= f.text_field :publish_date, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :description, class: 'bmd-label-floating' %>
				<%= f.text_area :description, class: 'form-control' %>
			</div>
			<div class="form-group">
				<div id="book_thumbnail"></div>
				<%= f.text_area :image_url, class: 'form-control' %>
			</div>
      <div class="form-group">
				<%= f.label :textship, class: 'bmd-label-floating' %>
				<%= f.text_area :textship, class: 'form-control' %>
			</div>

			<div class="form-row text-center">
      <div class="col-12">
      <%= f.submit "Save Changes", class: "btn btn-outline-primary" %>
      </div>
　　　 </div>
		<% end %>

		<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 2MB. Please choose a smaller file.');
    }
  });
</script>
	</div>
</div>

app/views/books/index.html.erb
<p class="text-center mt-5">Total number of Equipments : <%= @books_count %></p>
<input class="form-control mr-sm-2" type="form" id="form" placeholder="Search :  title or author" aria-label="Title or Author" style="width: 200px;">
<ul id="result">
</ul>

<%= paginate @books %>

<div class="row mt-5 d-flex">
	<% @books.each do |book| %>
		<div class="book text-center">
			<div class="bookcontainer">
          <a href="/books/<%= book.id %>"><img src="<%= book.image_url %>" onError="this.onerror=null;this.src='/noimage.png';" height="170"/></a>
          <p><%= link_to book.title, book %></p>
        </div>
		</div>
	<% end %>
</div>

<%= paginate @books %>

<script>
$(document).on('turbolinks:load', function(){
$(document).on('keyup', '#form', function(e){ 
  e.preventDefault();
	var input = $.trim($(this).val());
	
	if(input.length != 0){
  
  $.ajax({
    url: '/books/search',
		type: 'GET',
    data: ('keyword=' + input),
    processData: false,
    contentType: false,
    dataType: 'json'
	})
		
  .done(function(data){
    $('#result').find('a').remove();
    $('#result').find('br').remove();
    $(data).each(function(i, book){
			$('#result').append(`<a href="/books/${book.id}">` + book.title + ' - ' + book.author + `</a></br>`)
		});
	})

	}else{

    $.ajax({
    url: '/books/search',
		type: 'GET',
    data: ('keyword=' + input),
    processData: false,
    contentType: false,
    dataType: 'json'
	})
		
  .done(function(data){
    $('#result').find('a').remove();
    $('#result').find('br').remove();
	})

  }

});
});
</script>

app/views/books/new.html.erb
<%= javascript_pack_tag 'book/new.js' %>


<div class="row">
	<div class="col">
		<h1 class="text-center mt-5">Registration</h1>
		<%= render partial: 'isbn_reader' %>
		<%= form_with model: @book ,local: true do |f| %>
			<div class="search_book">
				<div class="search_title">
					<label>book name</label>
					<input type="text" id="search_title">
					<input class="btn btn-danger" type="button" id="title_search_button" value="Search">
				</div>
				<div class="search_isbn">
					<label>Isbn</label>
					<%= f.number_field :isbn %>
					<input class="btn btn-danger" type="button" id="isbn_search_button" value="Search">
				</div>
			</div>

			<div class="form-group">
				<%= f.label :place_id , {class: 'bmd-label-floating'} %><span class="red">*</span>
				<%= f.collection_select :place_id, Place.all, :id, :name, {prompt: true} ,{:class => "form-control"} %>
			</div>
			<div class="form-group">
				<%= f.label :title, class: 'bmd-label-floating' %><span class="red">*</span>
				<%= f.text_field :title, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :author, class: 'bmd-label-floating' %>
				<%= f.text_field :author, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :publisher, class: 'bmd-label-floating' %>
				<%= f.text_field :publisher, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :publish_date, class: 'bmd-label-floating' %>
				<%= f.text_field :publish_date, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :description, class: 'bmd-label-floating' %>
				<%= f.text_area :description, class: 'form-control' %>
			</div>
			
			<div class="form-group">
				<div id="book_thumbnail"></div>
				<%= f.text_area :image_url, class: 'form-control' %>
			</div>
      <div class="form-group">
				<%= f.label :textship, class: 'bmd-label-floating' %>
				<%= f.text_area :textship, class: 'form-control' %>
			</div>

			<div class="form-row text-center">
      <div class="col-12">
      <%= f.submit "Register New Book", class: "btn btn-outline-primary" %>
      </div>
　　　 </div>
		<% end %>
	</div>
</div>

app/views/books/show.html.erb
<h1 class="mt-5 text-center"><%= @book.title %></h1>
<div class="text-center mt-4 mb-4">
  <img height="160" src="<%= @book.image_url %>"　onError="this.onerror=null;this.src='/noimage.png';%>">
  <%= form_with model: @book ,local: true do |f| %>
　　　　<div class="form-group">
				<%= f.label :last_rental, class: 'bmd-label-floating' %>
				<%= f.text_field :last_rental, value: @user.name, class: 'form-control text-center'%>
			</div>
      <div class="form-row text-center">
      <div class="col-12">
      <%= f.submit "Rental", class: "btn btn-outline-primary" %>
      </div>
      </div>
　<% end %>
</div>
<table class="table">
  <tbody>
    <tr>
      <th scope="row">Last rental</th>
      <td><%= @book.last_rental %></td>
    </tr>
    <tr>
      <th scope="row">Updated at</th>
      <td><%= @book.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
    </tr>
    <tr>
      <th scope="row">Place</th>
      <td><%= @book.place.name %></td>
    </tr>
    <tr>
      <th scope="row">Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th scope="row">Description</th>
      <td><%= @book.description %></td>
    </tr>
    <tr>
      <th scope="row">Publisher</th>
      <td><%= @book.publisher %></td>
    </tr>
    <tr>
      <th scope="row">Publish_date</th>
      <td><%= @book.publish_date %></td>
    </tr>
    <tr>
      <th scope="row">Page count</th>
      <td><%= @book.page_count %></td>
    </tr>
    <tr>
      <th scope="row">Textship</th>
      <td><%= @book.textship %></td>
    </tr>
  </tbody>
</table>
<div class="text-center mt-4 mb-4">
<%= link_to "Edit", edit_book_path(@book), class: "btn btn-outline-dark" %> | 
<%= link_to "Delete", @book, class: "btn btn-outline-dark", method: :delete,
                                  data: { confirm: "Delete?" } %>
 
</div>           

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-light bg-light fixed-bottom p-1">
  <a class="navbar-brand footer p-1" href="#">
    footerです
  </a>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!--<a class="navbar-brand" href="/">Vision Equipment</a> -->
  <%= link_to "Vision Equipment", root_path, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to 'list', books_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'registration', new_book_path, data: {"turbolinks" => false}, class: 'nav-link' %>
      <li class="nav-item">
        <%#= link_to "About", about_path, class: 'nav-link' %>
      </li>
    </ul>

    <ul class="navbar-nav">
     <li class="nav-item">
        <%= link_to "Log in", login_path, class: "btn btn-outline-dark" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log out", logout_path, class: "btn btn-outline-dark", method: :delete %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VisionEquipment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>  
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
        <%= yield %>
      </div>
      <%#= debug(params) if Rails.env.development? %>
    <%#= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>Hello</h1>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  now creating
</p>

app/views/static_pages/home.html.erb
<div class="container home">
  <div class="jumbotron">
    <h1 class="display-4">Vision Equipment!</h1>
    <%= link_to "Log in now!", login_path, class: "btn btn-lg btn-primary" %>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a href="/books/index" class="btn btn-raised btn-info" role="button" aria-pressed="true">list</a>
    <%= link_to 'registration', new_book_path, data: {"turbolinks" => false}, class: 'btn btn-raised btn-success' %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <h1 class="text-center mt-5">Sign up</h1>
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, class: 'bmd-label-floating' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, class: 'bmd-label-floating' %>
      <%= f.email_field :email, class: 'form-control' %>

      <div class="text-center">
      <%= f.submit "Create my account", class: "btn btn-outline-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container home">
  <div class="jumbotron">
  <h1 class="display-4">Welcome back</h1>
    <h1 class="h5">Name：<span style="font-size:1.5em;" class="text-primary"><%= @user.name %></span></h1>
    <h1 class="h5">Email：<span style="font-size:1.5em;" class="text-primary"><%= @user.email %></span></h1>
    <hr class="my-4">
    <h1 class="display-4">Let's rental !</h1>
  
    <%= link_to 'list', books_path, class: 'btn btn-raised btn-info' %>
    <%= link_to 'registration', new_book_path, class: 'btn btn-raised btn-success' %>
  
    <!--
    <h1 href="../../books/index" class="btn btn-raised btn-info" role="button" aria-pressed="true">list</h1>
    <h1 href="../../books/new" class="btn btn-raised btn-success" role="button" aria-pressed="true">registration</h1>
    -->
    
    </ul>
  </div>
</div>